//Get all contacts
GET http://localhost:3000/contact
###
//Get Contacts by ID
GET http://localhost:3000/contact/644faaa3e7f43a0e5b67a9b8
###
//Get all contacts using render
GET https://codewithlaurels-srvc.onrender.com/contact
//Get contacts by ID using render
###
DELETE http://localhost:3000/contact/645d2591afdd725ea69f2d50
###
PUT http://localhost:3000/contact/644faaa3e7f43a0e5b67a9b8 HTTP/1.1 content-type: application/json

{"firstName": "John","lastName": "Snow","email": "matthew.snow@gmail.com","favoriteColor": "blue","birthday": "07-09-1998"}
###
POST http://localhost:3000/contact HTTP/1.1 Content-Type: application/json 

{"firstName":"Jane","lastName":"Smiths","email":"janesmiths@gmail.com","favoriteColor":"green","birthday": "1995-05-10"}

### CREATE A RANDOM CONTACT WITH FAKE DATA
POST  http://localhost:3000/contact-generator HTTP/1.1 Content-Type: application/json
### CREATE A RANDOM CONTACT WITH FAKE DATA ON RENDER
POST https://codewithlaurels-srvc.onrender.com/contact-generator
###
GET https://codewithlaurels-srvc.onrender.com/api-docs



 
